package com.example.eunoia.ui.theme

import androidx.compose.ui.graphics.Color

val background = Color(0xFFFDF5ED)
val darkModeBackground = Color(0xFF2B2B2B)
val emptyRoutineBackground = Color(0xFFB1BEE3)
val surpriseMeRoutineBackground = Color(0xFFD8EDED)
val Grey = Color(0xFF818181)
val Black = Color(0xFF000000)
val ButtonColor = Color(0xFFB1BEE3)
val White = Color(0xFFFFFFFF)
val Red = Color(0xFFC6413C)
val Blue = Color(0xFF264190)
val ArticleBackground = Color(0xFFEFEDE7)
val MixerBackground1 = Color(0xFFDAD4EC)
val MixerBackground2 = Color(0xFFF3E7E9)
val Mixer1 = Color(0xFFEBBA9A)
val Mixer2 = Color(0xFFBCDBDB)
val Mixer3 = Color(0xFFB1BEE3)
val Mixer4 = Color(0xFFEEB9CE)
val Mixer5 = Color(0xFF576693)
val Mixer6 = Color(0xFFA9ECC4)
val Mixer7 = Color(0xFFEB9A9A)
val Mixer8 = Color(0xFFBC8450)
val Mixer9 = Color(0xFF706969)
val Mixer10 = Color(0xFF78A6BA)
val Control1 = Color(0xFFF3E7E9)
val Control2 = Color(0xFFE3EEFF)
val ControlPanelManualBackground = Color(0xFFEEB9CE)
val TipBackground = Color(0xFFFEE5B6)
val OtherUsersFeedbackBackground = Color(0xFFDAD4EC)
val SettingsBlockBackground = Color(0xFFF6EAE3)
val SettingsEditBackground = Color(0xFFD8EDED)
val createNewSlumberPartyBackground = Color(0xFFEBBA9A)
val ratingStarUnselected = Color(0xFFF3E7E9)
val ratingStarSelected = Color(0xFFF6D7DE)
val textRatingBackground = Color(0xFFF6D7DE)
val RatingDropdownBackground = Color(0xFFF3E7E9)
val RatingDropdownText = Color(0xFFEEB9CE)
val PricingPlanBackground = Color(0xFFFAE3EC)
val ContributorSubscribeButtonBackground = Color(0xFFFBC2EB)